### ISSUE TITLE
Muhonmourn3 ROM version subslot issue

### ISSUE THREAD

**Issue by abekermsx** [Danjovic/MSX#2]
The ROM version of Muhonmourn3 does not always work if the cartridge is in a subslot (depending on the machine configuration, in blueMSX "MSX2 - Japanese" it returns to BASIC, but it does run the game in the MSXturboR configuration).

I use the routines below for creating slot IDs of what is currently selected in page 1 (the ROM) and page 3 (RAM), you can use these slot IDs with the BIOS routine ENASLT to select the appropriate (sub)slots.

get_page1_slot:
	call RSLREG     ; Read the primary slots register
	rrca
	rrca
	and 3
	ld c,a
	ld b,0
	ld hl,EXPTBL	; HL = Address of the secondary slot flags table
	add hl,bc
	ld a,(hl)
	and $80		; Keep the bit 7 (secondary slot flag)
	or c
	ld c,a
	inc hl
	inc hl
	inc hl
	inc hl		; HL =  Address of the secondary slot register in the secondary slot register table
	ld a,(hl)
	and $0c
	or c
	ret

get_page3_slot:
	call RSLREG     ; Read the primary slots register
	rlca
	rlca
	and 3
	ld c,a
	ld b,0
	ld hl,EXPTBL	; HL = Address of the secondary slot flags table
	add hl,bc
	ld a,(hl)
	and $80		; Keep the bit 7 (secondary slot flag)
	or c
	ld c,a
	inc hl
	inc hl
	inc hl
	inc hl		; HL =  Address of the secondary slot register in the secondary slot register table
	ld a,(hl)
	and $c0
        rrca
        rrca
        rrca
        rrca
	or c
	ret

**Comment by Danjovic** [comment]
I have updated the page 1 slot detection and tested on blueMSX w/ Japanese MSX2 configuration and it is working now.
I am considering that at the moment that the BIOS executes the game, the whole RAM is already selected and visible to Z80, wherever it is.
I am still switching back page 1 to the same page as the BIOS ROM at the end, because I didn't figure out why the game needs page 1 active. Maybe the Tonyu engine uses some BASIC functions, but I haven't investigated that further.
Thanks for the help. I will upload the updated code.
